version: '3.8'

networks:
  1panel-network:
    external: true

services:
  gcli2api:
    image: ghcr.io/zhongruan0522/geminicli2api:分支名
    container_name: geminicli2api
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - "7861:7861"
    environment:
      - HOST=0.0.0.0
      - PORT=7861
      - API_PASSWORD=your_api_key
      - PANEL_PASSWORD=your_password
      # - OAUTH_PROXY_URL=https://google-proxy.ai6.me/oauth2
      # - GOOGLEAPIS_PROXY_URL=https://google-proxy.ai6.me/api
      # - RESOURCE_MANAGER_API_URL=https://google-proxy.ai6.me/crm
      # - SERVICE_USAGE_API_URL=https://google-proxy.ai6.me/usage
      # - CODE_ASSIST_ENDPOINT=https://google-proxy.ai6.me/code
      - CALLS_PER_ROTATION=100
      - DAILY_LIMIT_PRO_MODELS=75
      - DAILY_LIMIT_TOTAL=600
      - OAUTH_PROXY_URL=https://gcli-api.sukaka.top/oauth2
      - GOOGLEAPIS_PROXY_URL=https://gcli-api.sukaka.top/googleapis
      - RESOURCE_MANAGER_API_URL=https://gcli-api.sukaka.top/cloudresourcemanager
      - SERVICE_USAGE_API_URL=https://gcli-api.sukaka.top/serviceusage
      - CODE_ASSIST_ENDPOINT=https://google-proxy.ai6.me/code
    volumes:
      - ./data/creds:/app/creds
      - ./var/data/creds/apilog.csv:/app/apilog.csv
      - ./var/data/creds/call_trace.log:/app/call_trace.log
