version: '3.8'

networks:
  1panel-network:
    external: true

services:
  gcli2api:
    image: ghcr.io/zhongruan0522/geminicli2api:分支名
    container_name: geminicli2api
    restart: unless-stopped
    networks:
      - 1panel-network
    environment:
      - HOST=0.0.0.0
      - PORT=7861
      - API_PASSWORD=your_api_key
      - PANEL_PASSWORD=your_password
      - OAUTH_PROXY_URL=https://oauth2.googleapis.com
      - GOOGLEAPIS_PROXY_URL=https://www.googleapis.com
      - RESOURCE_MANAGER_API_URL=https://cloudresourcemanager.googleapis.com
      - SERVICE_USAGE_API_URL=https://serviceusage.googleapis.com
      - CODE_ASSIST_ENDPOINT=https://cloudcode-pa.googleapis.com
      - CALLS_PER_ROTATION=100
      - DAILY_LIMIT_PRO_MODELS=75
      - DAILY_LIMIT_TOTAL=600
    volumes:
      - ./data/creds:/app/creds
      - ./var/data/creds/apilog.csv:/app/apilog.csv
      - ./var/data/creds/call_trace.log:/app/call_trace.log